name = "inbucks-fullstack"
main = "./functions"
compatibility_date = "2026-04-03"

[build]
command = "npm install"

[site]
bucket = "."
entry-point = "functions"

[env.production]
# Add your Cloudflare Pages defaults or variables here

[vars]
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_ADMIN_CHAT_ID = ""
TELEGRAM_CALLBACK_TOKEN = ""
